package learn;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JLabel;
import javax.swing.JButton;


public class CelsiusConverterGUI extends javax.swing.JFrame {
    
   /** Creates new form CelsiusConverterGUI */
   public CelsiusConverterGUI() {
       initComponents();
   }
    
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents() {
       tempTextField = new javax.swing.JTextField();
       celsiusLabel = new javax.swing.JLabel();
       convertButton = new javax.swing.JButton();
       fahrenheitLabel = new javax.swing.JLabel();
       JLabel resetLabel = new JLabel();
       JButton resetButton = new JButton();
       

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setTitle("Celsius Converter");

       celsiusLabel.setText("Celsius");

       convertButton.setText("Convert");
       convertButton.addActionListener(
    		   new java.awt.event.ActionListener() 
    		   {
    			   public void actionPerformed(java.awt.event.ActionEvent evt) 
    			   {
    				   convertButtonActionPerformed(evt);
    			   }
    		   }
    		   );

       fahrenheitLabel.setText("Fahrenheit");
       
       resetLabel.setText("Reset to 0");
       resetButton.setText("Reset");
       resetButton.addActionListener(
    		   new ActionListener() {
				@Override
				public void actionPerformed(ActionEvent e) 
					{
						resetActionButtonPerformed(e);					
					}
    		   } 		   
    	);
       resetButton.setToolTipText("Reset the value");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(tempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(celsiusLabel))
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(convertButton)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(fahrenheitLabel))
                   .addGroup(layout.createSequentialGroup()
                	   .addComponent(resetButton)
                	   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                	   .addComponent(resetLabel)))
               .addContainerGap(27, Short.MAX_VALUE))
       );
       
       resetButton.setEnabled(true);

       layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {convertButton, tempTextField});

       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(tempTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(celsiusLabel))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(convertButton)
                   .addComponent(fahrenheitLabel))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            		   .addComponent(resetButton)
            		   .addComponent(resetLabel))
               .addContainerGap(21, Short.MAX_VALUE))
       );
       pack();
   }// </editor-fold>//GEN-END:initComponents

   private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
//Parse degrees Celsius as a double and convert to Fahrenheit
       int tempFahr = (int)((Double.parseDouble(tempTextField.getText()))
           * 1.8 + 32);
       fahrenheitLabel.setText(tempFahr + " Fahrenheit");
   }//GEN-LAST:event_convertButtonActionPerformed
   
   private void resetActionButtonPerformed(ActionEvent e)
   {
	   fahrenheitLabel.setText("0 Fahrenheit");
   }
    
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new CelsiusConverterGUI().setVisible(true);
           }
       });
   }
    
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel celsiusLabel;
   private javax.swing.JButton convertButton;
   private javax.swing.JLabel fahrenheitLabel;
   private javax.swing.JTextField tempTextField;
   // End of variables declaration//GEN-END:variables
    
}